### PR TITLE
arm: dts: rock 3a/b: enable vdd_npu during power on

### PR DESCRIPTION
**Pull request by Ken-Vamrs**

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
1. commit消息里面说一下这个修改有什么效果。比如不开启则linux不能使用npu
2. 可以检查一下其他RK356X的产品是否需要同样修改

**Comment by Ken-Vamrs** [comment]
> 1. commit消息里面说一下这个修改有什么效果。比如不开启则linux不能使用npu
> 2. 可以检查一下其他RK356X的产品是否需要同样修改

再添加cm3 cm3i的修改

**Comment by RadxaYuntian** [comment]
3c和cm3s也打开吧

**Comment by RadxaYuntian** [comment]
@RadxaNaoki Do you think if we can upstream this change? This regulator needs to be enabled for NPU to work in Rockchip Linux. However, since U-Boot uses mainline Linux dts, and mainline Linux does not support NPU, I'm not sure if this can be something we submit to U-Boot.

**Comment by RadxaNaoki** [comment]
@RadxaYuntian it's possible to add new properties into u-boot specific dtsi (board-name-u-boot.dtsi) regardless of mainline kernel implementation.

about rock-3b, it must be submitted/accepted to mainline linux first.

**Review by RadxaYuntian — APPROVED** [review]

**Pull request merged**
