### PR TITLE
enable m.2 e-key pcie

### PR DESCRIPTION
**Pull request by pykpkg47**
enable m.2 e-key pcie so that boot with radxa m.2 e-key  extension is possible

### CODE REVIEW

**Comment by RadxaStephen** [comment]
Thanks for your work.
To make it a format patch, would you please add your e-mail and Signed-off-by to the git message?
Also check the title.

Like this

```
Author: FUKAUMI Naoki <naoki@radxa.com>
Date:   Tue Aug 6 10:18:42 2024 +0900

    arm: dts: rockchip: remove upstreamed props for Radxa ROCK 3A
    
    "sfc" node was already upstreamed. remove unnecessary properties from
    u-boot.dtsi.
    
    Signed-off-by: FUKAUMI Naoki <naoki@radxa.com>
    Reviewed-by: Kever Yang <kever.yang@rock-chips.com>
```

**Comment by pykpkg47** [comment]
> Thanks for your work. To make it a format patch, would you please add your e-mail and Signed-off-by to the git message? Also check the title.
> 
> Like this
> 
> ```
> Author: FUKAUMI Naoki <naoki@radxa.com>
> Date:   Tue Aug 6 10:18:42 2024 +0900
> 
>     arm: dts: rockchip: remove upstreamed props for Radxa ROCK 3A
>     
>     "sfc" node was already upstreamed. remove unnecessary properties from
>     u-boot.dtsi.
>     
>     Signed-off-by: FUKAUMI Naoki <naoki@radxa.com>
>     Reviewed-by: Kever Yang <kever.yang@rock-chips.com>
> ```

done, but used my github username instead of real name(  prefer to be anonym)

**Comment by nascs** [comment]
tested just now, and it works.

**Comment by RadxaStephen** [comment]
Thanks. @pykpkg47 @nascs 

I merged it.

**Pull request closed without merging**
