### PR TITLE
board: dts: add rk3588 fxblox-rk1 board device tree and defconfig

### PR DESCRIPTION
**Pull request by mahdichi**
add rk3588 fxblox-rk1 board

### CODE REVIEW

**Comment by RadxaStephen** [comment]
Hi, @mahdichi 

I use `git show <git-commit-id>` to view your patch.
I can see there are some unnecessary space and line.
Please remove them.

For example

```
+ &pcie30phy {
+        u-boot,dm-pre-reloc;
+        status = "okay";
+ };
+ 
+ 
+ &usb2phy2_grf {
+        u-boot,dm-pre-reloc;
+        status = "okay";
+        phy-supply = <&vcc5v0_host>;
+ };
```

And please add one line between two nodes in dts file.

```
+ &usb2phy2_grf {
+        u-boot,dm-pre-reloc;
+        status = "okay";
+        phy-supply = <&vcc5v0_host>;
+ };
+ &u2phy2 {
+        u-boot,dm-pre-reloc;
+        status = "okay";
+        phy-supply = <&vcc5v0_host>;
+ };
```

**Comment by mahdichi** [comment]
Hi @RadxaStephen
I correct the spaces problem.

**Comment by RadxaStephen** [comment]
Hi, I use `vim` and command `set list`, I still see many space from line to line 7 to line 221 in dts.
```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)$
/*$
 * Copyright (c) 2021 Rockchip Electronics Co., Ltd$
 *$
 */$
$
 /dts-v1/;$
 #include "rk3588.dtsi"$
 #include "rk3588-u-boot.dtsi"$
 #include <dt-bindings/input/input.h>$
 $
 / {$
^I model = "FxBlox RK1";$
^I compatible = "Functionland,fxblox-rk1", "rockchip,rk3588";$
 $
^I chosen {$
^I^I stdout-path = &uart2;$
^I^I u-boot,spl-boot-order = &spi_nor, &sdmmc, &sdhci, &spi_nand; $
^I };$
 $
^I vcc12v_dcin: vcc12v-dcin {$
^I^I u-boot,dm-pre-reloc;$
^I^I compatible = "regulator-fixed";$
^I^I regulator-name = "vcc12v_dcin";$
^I^I regulator-always-on;$
^I^I regulator-boot-on;$
^I^I regulator-min-microvolt = <12000000>;$
^I^I regulator-max-microvolt = <12000000>;$
^I };$
 $
^I vcc5v0_sys: vcc5v0-sys {$
^I^I u-boot,dm-pre-reloc;$
^I^I compatible = "regulator-fixed";$
^I^I regulator-name = "vcc5v0_sys";$
^I^I regulator-always-on;$
^I^I regulator-boot-on;$
^I^I regulator-min-microvolt = <5000000>;$ 
^I^I regulator-max-microvolt = <5000000>;$ 
^I^I vin-supply = <&vcc12v_dcin>;$
^I };$
 $
^I vcc3v3_pcie30: vcc3v3-pcie30 {$
^I^I u-boot,dm-pre-reloc;$
^I^I compatible = "regulator-fixed";$
^I^I regulator-name = "vcc3v3_pcie30";$
```

Seems caused by this commit https://github.com/functionland/u-boot/commit/989d8b88299c342fcf4aa9da87d69de7f5568eb0

**Comment by mahdichi** [comment]
@RadxaStephen 
I correct all leading spaces.

**Comment by RadxaStephen** [comment]
Merged.

**Pull request closed without merging**
