### PR TITLE
board: evb_rk3588: add get rtc device address to select dtb for CM5

### PR DESCRIPTION
**Pull request by RadxaMitchell**
The cm5-io has the same hw_id value as the cm5-rpi-cm4-io, and the corresponding dtb file needs to be selected by obtaining the address of the rtc device on the I2C bus.

The rtc device of cm5-io is on the I2C6 bus.
The rtc device for cm5-rpi-cm4-io is on the I2C7 bus. Both rtc devices have address 0x51.

### CODE REVIEW

**Review by RadxaYuntian — COMMENTED** [review]
这会影响用户基于树莓派定制底板的使用，如果没有包含rtc的话就会启动到我们cm5的dtb，还是不要做这种检测了吧

**Comment by RadxaYuntian** [comment]
@StephenInVamrs 另外硬件id需要有一个留空的值不匹配任何产品，用于客户定制项目使用定制dtb

**Comment by RadxaStephen** [comment]
那就不弄 cm5 io / rpicm4io 的检测。

**Comment by RadxaYuntian** [comment]
除非看看树莓派底板有没有什么id电路

**Pull request closed without merging**
